const express = require("express");
const app = express();

const port = 3000;

app.post("/link", async function (req, res) {
  try {
    res.json({
      link: [
        "https://vt.tiktok.com/ZSFfsnYKy/",
        "https://vt.tiktok.com/ZSFfsQUkT/",
        "https://vt.tiktok.com/ZSFfsQ6ng/",
        "https://vt.tiktok.com/ZSFfswAw2/",
        "https://vt.tiktok.com/ZSFfsK1aE/",
        "https://vt.tiktok.com/ZSFfs96Ce/",
        "https://vt.tiktok.com/ZSFfsCMGW/",
        "https://vt.tiktok.com/ZSFfsgs9N/",
        "https://vt.tiktok.com/ZSFfsm4d9/",
        "https://vt.tiktok.com/ZSFfsvGoL/",
        "https://vt.tiktok.com/ZSFfs31yX/",
        "https://vt.tiktok.com/ZSFfs7q4h/",
        "https://vt.tiktok.com/ZSFfsgHCy/",
        "https://vt.tiktok.com/ZSFfs3vgR/",
        "https://vt.tiktok.com/ZSFfsQy8T/",
        "https://vt.tiktok.com/ZSFfsGjxf/",
        "https://vt.tiktok.com/ZSFfsQtbu/",
        "https://vt.tiktok.com/ZSFfsCrLe/",
        "https://vt.tiktok.com/ZSFfsvb67/",
        "https://vt.tiktok.com/ZSFfsp1xc/",
        "https://vt.tiktok.com/ZSFfs3aGa/",
        "https://vt.tiktok.com/ZSFfsp77C/",
        "https://vt.tiktok.com/ZSFfsHMYT/",
        "https://vt.tiktok.com/ZSFfsWNG3/",
        "https://vt.tiktok.com/ZSFfsVsuk/",
        "https://vt.tiktok.com/ZSFfssn9u/",
        "https://vt.tiktok.com/ZSFfs3t6w/",
        "https://www.tiktok.com/@editor_ni_bianca_56/video/7288446566031985926",
        "https://vt.tiktok.com/ZSFfsXfnn/",
        "https://vt.tiktok.com/ZSFfsncjn/",
        "https://vt.tiktok.com/ZSFfsHDtB/",
        "https://vt.tiktok.com/ZSFfs98hH/",
        "https://vt.tiktok.com/ZSFfsqsQC/",
        "https://vt.tiktok.com/ZSFfGFESX/",
        "https://vt.tiktok.com/ZSFfGrSJS/",
        "https://vt.tiktok.com/ZSFfG6UE3/",
        "https://vt.tiktok.com/ZSFfGyh2r/",
        "https://vt.tiktok.com/ZSFfGRUSa/",
        "https://vt.tiktok.com/ZSFfGU4Eb/",
        "https://vt.tiktok.com/ZSFfGSGGC/",
        "https://vt.tiktok.com/ZSFfGDd4d/",
        "https://vt.tiktok.com/ZSFfG26J9/",
        "https://vt.tiktok.com/ZSFfGDU3x/",
        "https://vt.tiktok.com/ZSFfsoTq5/",
        "https://vt.tiktok.com/ZSFfsEoga/",
        "https://vt.tiktok.com/ZSFfGDsNM/",
        "https://vt.tiktok.com/ZSFfGdKrF/",
        "https://vt.tiktok.com/ZSFfGFNU5/",
        "https://vt.tiktok.com/ZSFfGDCWd/",
        "https://vt.tiktok.com/ZSFfG8FVD/",
        "https://vt.tiktok.com/ZSFfG1gJW/",
        "https://vt.tiktok.com/ZSFfG13qG/",
        "https://vt.tiktok.com/ZSFfGr6DK/",
        "https://vt.tiktok.com/ZSFfGhwN5/",
        "https://vt.tiktok.com/ZSFfGkNq6/",
        "https://vt.tiktok.com/ZSFfG2tA9/",
        "https://vt.tiktok.com/ZSFfGD9Bd/",
        "https://vt.tiktok.com/ZSFfGYLeJ/",
        "https://vt.tiktok.com/ZSFfGLjde/",
        "https://vt.tiktok.com/ZSFfGYgJx/",
        "https://vt.tiktok.com/ZSFfG1cV1/",
        "https://vt.tiktok.com/ZSFfG81yv/",
        "https://vt.tiktok.com/ZSFfGJrEV/",
        "https://vt.tiktok.com/ZSFfGjJqj/",
        "https://vt.tiktok.com/ZSFfG6cwd/",
        "https://vt.tiktok.com/ZSFfGPxF9/",
        "https://vt.tiktok.com/ZSFfGbheo/",
        "https://vt.tiktok.com/ZSFfGpcVJ/",
        "https://vt.tiktok.com/ZSFfGsuD9/",
        "https://vt.tiktok.com/ZSFfGHAG3/",
        "https://vt.tiktok.com/ZSFfGHEwc/",
        "https://vt.tiktok.com/ZSFfGxeoQ/",
        "https://vt.tiktok.com/ZSFfGX76q/",
        "https://vt.tiktok.com/ZSFfGCan6/",
        "https://vt.tiktok.com/ZSFfGm2Kr/",
        "https://vt.tiktok.com/ZSFfG4gbj/",
        "https://vt.tiktok.com/ZSFfG5uLn/",
        "https://vt.tiktok.com/ZSFfG9MDy/",
        "https://vt.tiktok.com/ZSFfGg43L/",
        "https://vt.tiktok.com/ZSFfGbQkf/",
        "https://vt.tiktok.com/ZSFfG5ubD/",
        "https://vt.tiktok.com/ZSFfGWvas/",
        "https://vt.tiktok.com/ZSFfGHEwD/",
        "https://vt.tiktok.com/ZSFfGvmxX/",
        "https://vt.tiktok.com/ZSFfGattB/",
        "https://vt.tiktok.com/ZSFfGsmK5/",
        "https://vt.tiktok.com/ZSFfGPmWB/",
        "https://vt.tiktok.com/ZSFfGnemV/",
        "https://vt.tiktok.com/ZSFfGamak/",
        "https://vt.tiktok.com/ZSFfGvWam/",
        "https://www.tiktok.com/@dlmrnvls/video/7294492622809255174",
        "https://vt.tiktok.com/ZSFfGPs71/",
        "https://vt.tiktok.com/ZSFfGP5Cm/",
        "https://vt.tiktok.com/ZSFfGvJaA/",
        "https://vt.tiktok.com/ZSFfGmbjA/",
        "https://vt.tiktok.com/ZSFfGq3BF/",
        "https://vt.tiktok.com/ZSFfGVETK/",
        "https://vt.tiktok.com/ZSFfGGabs/",
        "https://vt.tiktok.com/ZSFfGH5J1/",
        "https://vt.tiktok.com/ZSFfGPkq1/",
        "https://vt.tiktok.com/ZSFfGpqoR/",
        "https://vt.tiktok.com/ZSFfGWd9m/",
        "https://vt.tiktok.com/ZSFfG9Ffc/",
        "https://vt.tiktok.com/ZSFfG5wAK/",
        "https://vt.tiktok.com/ZSFfGtM9X/",
        "https://vt.tiktok.com/ZSFfGuyFn/",
        "https://vt.tiktok.com/ZSFfGaTg8/",
        "https://vt.tiktok.com/ZSFfGGvvk/",
        "https://vt.tiktok.com/ZSFfGasrq/",
        "https://vt.tiktok.com/ZSFfGxJEY/",
      ],
    });
  } catch (error) {
    res.json({ error: "error fetching link" });
    console.error(error);
  }
});

app.listen(port, () => {
  console.log(`app listening on ${port}`);
});
